services:
  cli:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    develop:
      watch:
        - path: .
          action: sync
          target: /app
    
        - action: rebuild
          path: uv.lock

        - action: rebuild
          path: pyproject.toml


  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: $${POSTGRES_USER:admin}
      POSTGRES_PASSWORD: $${POSTGRES_PASSWORD:admin}
      POSTGRES_DB: $${POSTGRES_DB:library}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql


volumes:
  postgres-data:
