services:
  app:
    ports:
      - "8000:8000"

    command: ["uv", "run", "--no-dev", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
    develop:
      watch:
        - action: sync
          path: .
          target: /app

        - action: rebuild
          path: pyproject.toml

        - action: rebuild
          path: uv.lock

    

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
