"""Add new fields to books

Revision ID: 93179e3f4ed7
Revises: 6dcd76318460
Create Date: 2026-07-05 16:25:21.742249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93179e3f4ed7'
down_revision: Union[str, Sequence[str], None] = '6dcd76318460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_column('books', 'deleted_at')
    op.drop_column('books', 'published_year')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'description')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
