"""add book price, loan renewal and fine, timezone aware timestamps

Revision ID: 976dad5071a0
Revises: 682e1fffd382
Create Date: 2026-07-11 11:44:34.618715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '976dad5071a0'
down_revision: Union[str, Sequence[str], None] = '682e1fffd382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('loans', sa.Column('renew_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('loans', sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    op.add_column('loans', sa.Column('fine_paid', sa.Boolean(), nullable=False, server_default='False'))
    op.alter_column('loans', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('loans', 'returned_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'returned_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('loans', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('loans', 'fine_paid')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'renew_count')
    op.drop_column('books', 'price')
    # ### end Alembic commands ###
