"""add CANCELED and REJECTED to loan status

Revision ID: accb3238e6be
Revises: f7a0628eb57e
Create Date: 2026-07-06 04:24:42.112381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accb3238e6be'
down_revision: Union[str, Sequence[str], None] = 'f7a0628eb57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE loanstatus ADD VALUE 'canceled'")
    op.execute("ALTER TYPE loanstatus ADD VALUE 'rejected'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
