"""Partial Unique Constraint For ISBN of Book

Revision ID: f7a0628eb57e
Revises: 93179e3f4ed7
Create Date: 2026-07-05 18:39:25.772422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a0628eb57e'
down_revision: Union[str, Sequence[str], None] = '93179e3f4ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_index('ix_books_isbn_unique_active', 'books', ['isbn'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_isbn_unique_active', table_name='books', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    # ### end Alembic commands ###
