"""Add daily stats table

Revision ID: fe1e74bfe080
Revises: 976dad5071a0
Create Date: 2026-07-14 01:22:50.003761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1e74bfe080'
down_revision: Union[str, Sequence[str], None] = '976dad5071a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_statistics',
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('books_borrowed', sa.Integer(), nullable=False),
    sa.Column('books_returned', sa.Integer(), nullable=False),
    sa.Column('active_loans', sa.Integer(), nullable=False),
    sa.Column('overdue_loans', sa.Integer(), nullable=False),
    sa.Column('active_members', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stat_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_statistics')
    # ### end Alembic commands ###
