name: Deploy to VM

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "Starting deployment..."
            cd ./lms

            git pull origin main

            echo "Building the project..."
            docker compose -f docker-compose.yml build


            echo "Migrating database..."
            docker compose -f docker-compose.yml run --rm app uv run --no-dev alembic upgrade head

            echo "Starting new containers..."
            docker compose -f docker-compose.yml up -d

            echo "Deployment completed successfully!"
            echo "Cleaning up..."
            docker image prune -f